[features]
seeds = false
skip-lint = false
[programs.localnet]
zetteltute_anchor = "6t3Ca79eN9fDh7gmc3cVgMum7qAk3JRZgokNnL3TioKD"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/henning.kropp/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
